// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyzHacT_vo5geMhvEtniWaT5YYdL_hieQ',
    appId: '1:982457552345:web:aebff5e6c7d8dba80eddc8',
    messagingSenderId: '982457552345',
    projectId: 'clinic-notifications-153e3',
    authDomain: 'clinic-notifications-153e3.firebaseapp.com',
    storageBucket: 'clinic-notifications-153e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyog_NWuPP8ke1IQfdQk1kL9xxtMWaPb0',
    appId: '1:982457552345:android:5abe8141e4e3c5ed0eddc8',
    messagingSenderId: '982457552345',
    projectId: 'clinic-notifications-153e3',
    storageBucket: 'clinic-notifications-153e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBarkzxLxiX97VWtAUJTk8SLxpe5JWlzWI',
    appId: '1:982457552345:ios:d084c20b05bd85a20eddc8',
    messagingSenderId: '982457552345',
    projectId: 'clinic-notifications-153e3',
    storageBucket: 'clinic-notifications-153e3.firebasestorage.app',
    iosBundleId: 'com.example.clinicMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBarkzxLxiX97VWtAUJTk8SLxpe5JWlzWI',
    appId: '1:982457552345:ios:d084c20b05bd85a20eddc8',
    messagingSenderId: '982457552345',
    projectId: 'clinic-notifications-153e3',
    storageBucket: 'clinic-notifications-153e3.firebasestorage.app',
    iosBundleId: 'com.example.clinicMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyzHacT_vo5geMhvEtniWaT5YYdL_hieQ',
    appId: '1:982457552345:web:0ca1fdde00add7c50eddc8',
    messagingSenderId: '982457552345',
    projectId: 'clinic-notifications-153e3',
    authDomain: 'clinic-notifications-153e3.firebaseapp.com',
    storageBucket: 'clinic-notifications-153e3.firebasestorage.app',
  );
}
